version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vue-app2
    ports:
      - 8080:8080
  nginx:
    image: nginx:alpine
    container_name: nginx-app2
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
     # - ./certs:/certs
    ports:
      - 80:80
    depends_on:
      - app
